### ISSUE TITLE
请问怎么删除?

### ISSUE THREAD

**Issue by Blackcat308** [baulk/baulk#15]
已经按照文档说明执行了对应操作。但并没在右键菜单中看见。现在想卸掉、请问怎么卸载掉啊。

**Comment by fcharlie** [comment]
> 已经按照文档说明执行了对应操作。但并没在右键菜单中看见。现在想卸掉、请问怎么卸载掉啊。

右键运行 `script/uninstallmenu.bat` 删除右键菜单，删除 baulk 只需要删除 baulk 整个目录即可。

**Comment by Blackcat308** [comment]
右键以管理员运行 baulk 目录下的script/installmenu.bat，为什么在右键菜单里看不到任何与baulk的相关？
![image](https://user-images.githubusercontent.com/21216908/91513525-23a8b500-e917-11ea-9faf-baeaeb592488.png)

**Comment by fcharlie** [comment]
> 右键以管理员运行 baulk 目录下的script/installmenu.bat，为什么在右键菜单里看不到任何与baulk的相关？
> ![image](https://user-images.githubusercontent.com/21216908/91513525-23a8b500-e917-11ea-9faf-baeaeb592488.png)

那你运行 `script/installmenu.bat` 是不是以管理员权限运行？可以重新试一下。

![image](https://user-images.githubusercontent.com/6904176/91513717-96b22b80-e917-11ea-92ba-4fbc29b882d0.png)

**Comment by Blackcat308** [comment]
是以管理员权限运行的。但是并没有显示。

**Comment by fcharlie** [comment]
> 是以管理员权限运行的。但是并没有显示。

你先打开一个管理员控制台（Win+X），然后运行脚本看看，把输出打印出来：

![image](https://user-images.githubusercontent.com/6904176/91514449-63709c00-e919-11ea-9e25-c493827ce1b2.png)

**Comment by Blackcat308** [comment]
![image](https://user-images.githubusercontent.com/21216908/91514650-daa63000-e919-11ea-89d1-af4c1ac81769.png)

pwsh不是外部or内部命令。

**Comment by fcharlie** [comment]
> ![image](https://user-images.githubusercontent.com/21216908/91514650-daa63000-e919-11ea-89d1-af4c1ac81769.png)
> 
> pwsh不是外部or内部命令。

建议安装 powershell 7.0.2 https://github.com/PowerShell/PowerShell/releases/tag/v7.0.3

如果不想安装，可以修改 `install.bat` 将 pwsh 改为 powershell.  如果没有安装 PowerShell Core. baulkterminal 也可以运行，但会启动 cmd。

```bat
@echo off
powershell -NoProfile -NoLogo -ExecutionPolicy unrestricted -File "%~dp0installmenu.ps1" %*
```

**Comment by Blackcat308** [comment]
好了！谢谢。

**Comment by Blackcat308** [comment]
虽然现在是出来了 右键菜单点击了没反应- -！ 我先安装7.0.2试试

**Comment by fcharlie** [comment]
> 虽然现在是出来了 右键菜单点击了没反应- -！ 我先安装7.0.2试试

你安装 Windows Terminal 没有？

**Comment by Blackcat308** [comment]
正在安装

**Comment by Blackcat308** [comment]
废了。安装不上不是正版系统- -！

**Comment by fcharlie** [comment]
> 废了。安装不上不是正版系统- -！

你点击 baulk-dock 运行看看。

**Comment by Blackcat308** [comment]
没反应，那些选项切换了都不行 
![image](https://user-images.githubusercontent.com/21216908/91517899-88690d00-e921-11ea-8427-18726b8a87b6.png)

**Comment by fcharlie** [comment]
> 没反应，那些选项切换了都不行
> ![image](https://user-images.githubusercontent.com/21216908/91517899-88690d00-e921-11ea-8427-18726b8a87b6.png)

你的系统是什么版本？>=1903/1909

**Comment by Blackcat308** [comment]
![image](https://user-images.githubusercontent.com/21216908/91518934-e1d23b80-e923-11ea-93fb-5c3418038f7e.png)

**Comment by fcharlie** [comment]
@Blackcat308 Windows Terminal 好像需要 Windows 10 1903 或更高版本，然后如果你的系统是 x64 的你尽量使用 x64 的 baulk。x86 我这里运行正常，有点小错误，我会调查一下。

**Comment by fcharlie** [comment]
@Blackcat308 你打开 CMD 切换到 baulk bin 目录下，运行

```bat
baulk-exec -V cmd
```

看看输出结果。

**Comment by Blackcat308** [comment]
![image](https://user-images.githubusercontent.com/21216908/91527904-3f24b780-e939-11ea-9b09-62dc309f463d.png)
这是执行后打印的。我同时也换成了64的，不过也还是不行。

**Comment by fcharlie** [comment]
> ![image](https://user-images.githubusercontent.com/21216908/91527904-3f24b780-e939-11ea-9b09-62dc309f463d.png)
> 这是执行后打印的。我同时也换成了64的，不过也还是不行。

因为无论是 baulkterminal 还是 baulk-dock 最后都是运行的 baulk-exec 去启动一个 baulk 环境。这里看 baulk-exec 是运行成功的，为什么 baulkterminal 还有 baulk-dock 为啥运行不了这个要再分析看看。

**Comment by Blackcat308** [comment]
ok 了解，辛苦，谢谢！

**Comment by fcharlie** [comment]
@Blackcat308 你无法运行 baulkterminal 的原因可能是 installmenu.ps1 默认添加了 --vs 标志，你可以在文件中去掉重新设置开始菜单，或者升级 baulk 到 1.5.3.
