### ISSUE TITLE
可以对软件多个版本进行管理吗

### ISSUE THREAD

**Issue by zzy97mail** [baulk/baulk#16]

**Comment by zzy97mail** [comment]
部分电脑默认是不能直接使用pwsh的需要安装或配置PowerShell，配置右键的脚本推荐添加检测

**Comment by fcharlie** [comment]
> 部分电脑默认是不能直接使用pwsh的需要安装或配置PowerShell，配置右键的脚本推荐添加检测

这个可以做一下

**Comment by zzy97mail** [comment]
> > 部分电脑默认是不能直接使用pwsh的需要安装或配置PowerShell，配置右键的脚本推荐添加检测
> 
> 这个可以做一下

安装go的时候我注意到配置json中有一段
`"venv": {
        "category": "golang",
        "path": [
            "${BAULK_PKGROOT}\\bin",
            "${BAULK_VFS}\\go\\bin"
        ],
        "env": [
            "GOPATH=${BAULK_VFS}\\go",
            "GOENV=${BAULK_VFS}\\go\\env",
            "GO111MODULE=on",
            "GO_PROXY=https://goproxy.io"
        ]
    }`
它会自动配置系统的环境变量吗？但实际操作中 环境变量中未出现对应的配置

**Comment by fcharlie** [comment]
> > > 部分电脑默认是不能直接使用pwsh的需要安装或配置PowerShell，配置右键的脚本推荐添加检测
> > 
> > 
> > 这个可以做一下
> 
> 安装go的时候我注意到配置json中有一段
> `"venv": { "category": "golang", "path": [ "${BAULK_PKGROOT}\\bin", "${BAULK_VFS}\\go\\bin" ], "env": [ "GOPATH=${BAULK_VFS}\\go", "GOENV=${BAULK_VFS}\\go\\env", "GO111MODULE=on", "GO_PROXY=https://goproxy.io" ] }`
> 它会自动配置系统的环境变量吗？但实际操作中 环境变量中未出现对应的配置

这个是 baulk virtual environment 的一个机制，实际上 baulk 会创建一个隔离的环境变量 比如 baulk-exec -Ego pwsh 或者 baulkterminal - Ego 这样的方式加载 go 环境变量 json 中的BAULK_PKGROOT 会被 baulk-exec 推导
