### ISSUE TITLE
off-topic: any community channel?

### ISSUE THREAD

**Issue by chawyehsu** [baulk/baulk#27]
之前在 V2EX 看到宣传帖就关注了，对整个项目挺感兴趣和支持的，稍微尝试过一下，感觉还不太成熟，不过有些很亮眼的地方
。其实我有些想法，不过鉴于目前对项目整体不太熟悉，不好发表评论，我对 C/C++ 不是很了解，只能读个大概。作者有没有兴趣开个 Telegram group / Discord server 之类的讨论组给大家交流下？

_P.S. 我是 Scoop 维护者之一，虽然已经名存实亡。_

**Comment by fcharlie** [comment]
非常感谢你关注 baulk，baulk 的定位是一个极简的，绿色的，环境变量隔离的包管理器。这个工具是去年开始挖坑的，有很多有意思的技术运用进去了，比如 PE 文件格式的分析，从 Golang 移植过来的 ZIP/Tar 解压缩能力，Visual Studio 环境变量加载等等，当然也有很多不足，你如果有一些建议尽管在 Issues 中打开，如果你有兴趣也可以给 baulk 提交 PR。

Telegram group: https://t.me/joinchat/LmrxRCSpUu8wMTk1
