### ISSUE TITLE
如何通过一条命令安装baulk？

### ISSUE THREAD

**Issue by hmsjy2017** [baulk/baulk#28]
Scoop 和 Chocolatey 只需要一条命令就能安装（通过执行 ps1 脚本），希望 baulk 也能这样。

**Comment by fcharlie** [comment]
在我看来，这样做的意义不大，baulk 只需要下载解压到任意目录，而无需配置即可使用（只需双击 baulkterminal.exe 即可启动环境变量初始化成功的终端），scoop 的 install.ps1 则不然，它还需要一些额外的配置，所以并不是简单的压缩解压即可。

**Comment by fcharlie** [comment]
目前 2.2.0-beta0 已经提供安装包，可以下载后双击运行：https://github.com/baulk/baulk/releases/tag/2.2.0-beta0

该安装包不需要管理员权限。
