### ISSUE TITLE
兼容 scoop/chocolatey/winget 的 bucket

### ISSUE THREAD

**Issue by hmsjy2017** [baulk/baulk#29]
baulk 官方 bucket 中软件数量很少，无法满足日常需求。

**Comment by fcharlie** [comment]
baulk 设计机制和 scoop chocolatey winget 有很大的不同，baulk 更新喜欢绿色隔离，免安装，虚拟环境这样的机制，这就是得 bucket 有一些不兼容，要解决这个问题，只需要简单的移植一下即可。

**Comment by ArchGuyWu** [comment]
> baulk 设计机制和 scoop chocolatey winget 有很大的不同，baulk 更新喜欢绿色隔离，免安装，虚拟环境这样的机制，这就是得 bucket 有一些不兼容，要解决这个问题，只需要简单的移植一下即可。

那跟scoop的理念很像
