### ISSUE TITLE
软件缺少问题

### ISSUE THREAD

**Issue by chengnan049** [baulk/baulk#61]
对于现在的软件缺少问题应如何解决，看 Issues 有说过想要兼容 scoop 软件需要做一些适配，具体指的是？想要抛弃 scoop 全力转用 baulk（短时间内应该无法实现）

**Comment by fcharlie** [comment]
目前是做了 scoop 的兼容，但有一些限制，主要问题是目前 baulk 都是我一个人的业余维护，而我的工作都是用的 mac，没啥时间来做维护。

另外，还有一些其他的奇思妙想可以做，但目前没啥精力做这个。

**Comment by chengnan049** [comment]
巧了我也是用的是 macOS ，但仍希望支持该项目，Homebrew 4.0.0 的 JSON API 似乎是一个很不错的参考例子，详见 [Homebrew 升级 4.0.0，麦金塔上的啤酒会更香吗？ - 少数派](https://sspai.com/post/78587)

**Comment by fcharlie** [comment]
> 巧了我也是用的是 macOS ，但仍希望支持该项目，Homebrew 4.0.0 的 `JSON API` 似乎是一个很不错的参考例子，详见 [Homebrew 升级 4.0.0，麦金塔上的啤酒会更香吗？ - 少数派](https://sspai.com/post/78587)

基于 git 的包管理器确实存在一定的缺陷，包管理软件有很大的改进空间，值得思考，希望有时间能好好的研究下。
