### ISSUE TITLE
不能自定义安装目录吗？

### ISSUE THREAD

**Issue by ingxhe** [baulk/baulk#65]
不能自定义安装目录吗？

**Comment by fcharlie** [comment]
> 不能自定义安装目录吗？

可以不用安装 用便携模式，解压到你想放的目录 然后安装目录就在目录下

**Comment by ingxhe** [comment]
我的意思是自定义要安装软件的安装目录

**Comment by fcharlie** [comment]
> 我的意思是自定义要安装软件的安装目录

不支持配置，都能便携了，就没支持配置了。
